trigger:
- main

variables:
  BUILD_COMMIT: 876a17a55d859485dbeb505ddc4ad4f0369e47ff

jobs:
  - template: azure/posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-18.04
      matrix:
        py_3.6_32manylinux1:
          MB_PYTHON_VERSION: "3.6"
          PLAT: "i686"
          MB_ML_VER: "1"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.6_64manylinux1:
          MB_PYTHON_VERSION: "3.6"
          MB_ML_VER: "1"
        py_3.7_32manylinux1:
          MB_PYTHON_VERSION: "3.7"
          PLAT: "i686"
          MB_ML_VER: "1"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.7_64manylinux1:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "1"
        py_3.8_32manylinux1:
          MB_PYTHON_VERSION: "3.8"
          PLAT: "i686"
          MB_ML_VER: "1"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.8_64manylinux1:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "1"
        py_3.9_32manylinux1:
          MB_PYTHON_VERSION: "3.9"
          PLAT: "i686"
          MB_ML_VER: "1"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"
        py_3.9_64manylinux1:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "1"

  - template: azure/posix.yml
    parameters:
      name: macOS
      vmImage: macOS-10.14
      matrix:
        py_3.6_64:
          MB_PYTHON_VERSION: "3.6"
        py_3.7_64:
          MB_PYTHON_VERSION: "3.7"
        py_3.8_64:
          MB_PYTHON_VERSION: "3.8"
        py_3.9_64:
          MB_PYTHON_VERSION: "3.9"
