trigger:
- main

variables:
  BUILD_COMMIT: 876a17a55d859485dbeb505ddc4ad4f0369e47ff

jobs:
  - template: azure/posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-18.04
      matrix:
        py_3.7_64manylinux1:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "1"
